In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/customer-data/customer.csv


In [2]:
df=pd.read_csv('/kaggle/input/customer-data/customer.csv')

In [3]:
df.sample(5)

age  gender review education purchased
46   64  Female   Poor        PG        No
1    68  Female   Poor        UG        No
26   53  Female   Poor        PG        No
35   74    Male   Poor    School       Yes
15   75    Male   Poor        UG        No

In [4]:
df=df.iloc[:,2:]

In [5]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [8]:
x_train

review education
28     Poor    School
47     Good        PG
37  Average        PG
29  Average        UG
21  Average        PG
20  Average    School
43     Poor        PG
5   Average    School
10     Good        UG
1      Poor        UG
17     Poor        UG
22     Poor        PG
19     Poor        PG
40     Good    School
36     Good        UG
3      Good        PG
30  Average        UG
0   Average    School
42     Good        PG
8   Average        UG
2      Good        PG
34  Average    School
38     Good    School
9      Good        UG
33     Good        PG
27     Poor        PG
46     Poor        PG
7      Poor    School
12     Poor    School
13  Average    School
25     Good    School
16     Poor        UG
39     Poor        PG
49     Good        UG
14     Poor        PG
6      Good    School
26     Poor        PG
23     Good    School
4   Average        UG
24  Average        PG

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [11]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [12]:
x_train = oe.transform(x_train)

In [13]:
x_train

array([[0., 0.],
       [2., 2.],
       [1., 2.],
       [1., 1.],
       [1., 2.],
       [1., 0.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [0., 1.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [2., 0.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [1., 0.],
       [2., 0.],
       [0., 1.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [1., 2.]])

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
le=LabelEncoder()

In [16]:
le.fit(y_train)

LabelEncoder()

In [17]:
y_train= le.transform(y_train)

In [18]:
y_train

array([0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1])

In [19]:
y_test = le.transform(y_test)

In [20]:
y_test

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 0])

In [21]:
x_test = oe.transform(x_test)

In [22]:
x_test

array([[2., 2.],
       [2., 1.],
       [0., 0.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [0., 1.]])